<h1>Enginnering Planing and Codding V2</h1>

In [ ]:
# Importa o código principal
import sys
sys.path.append('C:\\Users\\Danilo Santos\\Desktop\\Qualificação PPGCC\\abordagem\\RFNS')

In [ ]:
from grimoire.ConfigurationEnginnering import ConfigurationEnginnering

In [ ]:
ce = ConfigurationEnginnering()

In [ ]:
dir(ce)

In [ ]:
ce.run_logging()

In [ ]:
dir(ce.logger)

In [ ]:
ce.logger.add('debug', 'msg log')

In [ ]:
from grimoire.EnginneringForest import EnginneringForest

In [ ]:
ef = EnginneringForest(select_features=3)
ef.run_logging()

In [ ]:
ef2 = EnginneringForest(select_features=3)

In [ ]:
dir(ef)

In [ ]:
dir(ef2.logger)

In [1]:
# Importa o código principal
import sys
sys.path.append('C:\\Users\\Danilo Santos\\Desktop\\Qualificação PPGCC\\abordagem\\RFNS')
from grimoire.EnginneringForest import EnginneringForest

In [2]:
import pandas as pd

import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, accuracy_score
from sklearn.ensemble import RandomForestClassifier

import matplotlib.pyplot as plt
from matplotlib.colors import ListedColormap

import seaborn as sns

In [3]:
df_heart = pd.read_csv('../datasets/heart.csv', engine='c', memory_map=True, low_memory=True)

X=df_heart[['age', 'sex', 'cp', 'trestbps',  'chol', 'fbs', 'restecg', 'thalach', 'exang', 
            'oldpeak', 'slope', 'ca', 'thal']]
# Labels
y=df_heart['target']

# Split dataset into training set and test set
# 70% training and 30% test
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=30, shuffle=True, stratify=y)

In [4]:
heart_accuracy_eg = []
heart_matrix_confusion_eg = []
n_estimators_eg = []
limit = int((X.shape[1] / 2) + 1)

for n_tree in range(limit):
    model_eg = EnginneringForest(select_features=n_tree+1)
    model_eg.fit(X_train, y_train)
    y_pred = model_eg.predict(X_test)

    mac = accuracy_score(y_test, y_pred)
    mcm = confusion_matrix(y_test,y_pred)
    
    heart_accuracy_eg.append(mac)
    heart_matrix_confusion_eg.append(mcm)
    n_estimators_eg.append(len(model_eg.estimators_))
    
    print('Acuracia = {0}'.format(mac))
    print("Matriz de confusao \n{0}".format(str(mcm)))
    print("N arvores = {0}".format(n_estimators_eg))

    del model_eg

Acuracia = 0.7912087912087912
Matriz de confusao 
[[28 13]
 [ 6 44]]
N arvores = [13]
Acuracia = 0.8241758241758241
Matriz de confusao 
[[33  8]
 [ 8 42]]
N arvores = [13, 78]
Acuracia = 0.8351648351648352
Matriz de confusao 
[[33  8]
 [ 7 43]]
N arvores = [13, 78, 286]
Acuracia = 0.8241758241758241
Matriz de confusao 
[[32  9]
 [ 7 43]]
N arvores = [13, 78, 286, 715]
Acuracia = 0.8241758241758241
Matriz de confusao 
[[31 10]
 [ 6 44]]
N arvores = [13, 78, 286, 715, 1287]
Acuracia = 0.8021978021978022
Matriz de confusao 
[[30 11]
 [ 7 43]]
N arvores = [13, 78, 286, 715, 1287, 1716]
Acuracia = 0.7912087912087912
Matriz de confusao 
[[29 12]
 [ 7 43]]
N arvores = [13, 78, 286, 715, 1287, 1716, 1716]
